const Sequelize = require('sequelize');

module.exports = class Post extends Sequelize.Model{
    static init(sequelize){
        return super.init({
            writer_uid:{
                type:Sequelize.STRING(30),
                allowNull:false,
            },
            cid:{
                type:Sequelize.STRING(100),
                allowNull:true,
            },
            isNotice:{
                type:Sequelize.STRING(10),
                allowNull:false,
            },
            isEvent:{
                type:Sequelize.STRING(250),
                allowNull:true,
                defaultValue:"",
            },
            text:{
                type:Sequelize.STRING(30),
                allowNull:true,
            },
            banner:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:false,
            },
            image:{
                type:Sequelize.STRING(10),
                allowNull:true,
            },
            file:{
                type:Sequelize.STRING(10),
                allowNull:true,
            },
            video:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0,
            },
            like_uid_list:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            participation_fee:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            participation_uid_list:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            paid_uid_list:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            comment_id_list:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            title:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            title:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            title:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            title:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
            title:{
                type:Sequelize.BOOLEAN,
                allowNull:false,
                defaultValue:true,
            },
        },{
            sequelize,
            timestamps:false,
            underscored:false,
            modelName:'Post',
            tableName:'posts',
            paranoid:false,
            charset:'utf8',
            collate:'utf8_general_ci',
        });
    }
    static associate(db){
        db.Club.hasMany(db.Club_user,{foreignKey:'cid',sourceKey:'id'});
        db.Club.hasMany(db.ApplicationForm,{foreignKey:'cid',sourceKey:'id'});
        db.Club.hasMany(db.User_favorite_club,{foreignKey:'cid',sourceKey:'id'});

        db.Club.belongsToMany(db.Hashtag,{through:'ClubHashtag',as:'hashtags'});
    }
};